set(_CATKIN_CURRENT_PACKAGE "bateria")
set(bateria_VERSION "0.0.0")
set(bateria_MAINTAINER "auto <auto@todo.todo>")
set(bateria_PACKAGE_FORMAT "1")
set(bateria_BUILD_DEPENDS "diagnostic_msgs" "roscpp" "std_msgs" "actionlib" "kobuki_msgs")
set(bateria_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "roscpp" "std_msgs" "actionlib" "kobuki_msgs")
set(bateria_BUILDTOOL_DEPENDS "catkin")
set(bateria_BUILDTOOL_EXPORT_DEPENDS )
set(bateria_EXEC_DEPENDS "diagnostic_msgs" "roscpp" "std_msgs" "actionlib" "kobuki_msgs")
set(bateria_RUN_DEPENDS "diagnostic_msgs" "roscpp" "std_msgs" "actionlib" "kobuki_msgs")
set(bateria_TEST_DEPENDS )
set(bateria_DOC_DEPENDS )
set(bateria_DEPRECATED "")